version: 2.1

jobs:
  build-neovim-arm64:
    machine:
      image: ubuntu-2204:current
    environment:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - checkout

      - run:
          name: 🔁 Ganti Mirror APT (anti 403)
          command: |
            sudo sed -i 's|http://archive.ubuntu.com/ubuntu|http://mirror.kku.ac.th/ubuntu|g' /etc/apt/sources.list
            sudo sed -i 's|http://security.ubuntu.com/ubuntu|http://mirror.kku.ac.th/ubuntu|g' /etc/apt/sources.list
            sudo apt-get update || true

      - run:
          name: 🧰 Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y \
              git curl wget unzip tar gzip ca-certificates \
              build-essential ninja-build gettext cmake \
              libtool libtool-bin autoconf automake pkg-config \
              qemu-user-static binfmt-support jq

      - run:
          name: 🐳 Enable QEMU Emulation + Docker Buildx
          command: |
            sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            sudo docker buildx create --use || true

      - run:
          name: 🛠️ Build Neovim ARM64 v0.10.0
          command: |
            mkdir -p output
            sudo docker run --rm --platform linux/arm64 \
              -v $PWD/output:/build \
              ubuntu:22.04 bash -c '
                set -e
                apt update &&
                apt install -y git ninja-build gettext cmake unzip curl build-essential \
                  libtool libtool-bin autoconf automake pkg-config tar coreutils &&
                curl -fsSL https://github.com/neovim/neovim/archive/refs/tags/v0.10.0.tar.gz -o neovim.tar.gz &&
                tar -xzf neovim.tar.gz &&
                cd neovim-0.10.0 &&
                make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=/build/nvim-arm64 -j2 &&
                make install &&
                mkdir -p /build/nvim-arm64/share/nvim &&
                cp -r runtime /build/nvim-arm64/share/nvim &&
                cd /build &&
                tar -czf nvim-arm64.tar.gz nvim-arm64 &&
                sha256sum nvim-arm64.tar.gz > sha256.txt
              '

      - run:
          name: ✅ Test Neovim Binary (ARM64)
          command: |
            sudo docker run --rm --platform linux/arm64 \
              -v $PWD/output/nvim-arm64:/nvim ubuntu:22.04 \
              bash -c '/nvim/bin/nvim --version || echo "❌ Neovim gagal jalan!"'

      - run:
          name: 📋 Cek Output
          command: |
            ls -lh output/
            cat output/sha256.txt

      - store_artifacts:
          path: output/nvim-arm64.tar.gz
          destination: nvim-arm64

      - store_artifacts:
          path: output/sha256.txt
          destination: sha256

      - run:
          name: 🚀 Upload ke GitHub Release
          command: |
            sudo apt-get install -y git curl jq
            TAG="v0.10.0-arm64"
            FILE="nvim-arm64.tar.gz"
            FILE_SHA="sha256.txt"
            GH_REPO="iyanldn/Ubuntu-V24.04"
            RELEASE_NAME="Neovim ARM64 v0.10.0"
            BODY="✅ Built via CircleCI on $(date +%Y-%m-%d)\n🔒 SHA256:\n$(cat output/sha256.txt)"

            cd output

            # Validasi file
            test -f "$FILE" || (echo "❌ File $FILE tidak ditemukan"; exit 1)
            test -f "$FILE_SHA" || (echo "❌ File $FILE_SHA tidak ditemukan"; exit 1)

            # Push tag (jika belum)
            git config --global user.email "ci@circleci"
            git config --global user.name "circleci-bot"
            git tag "$TAG" || true
            git push --tags "https://${GH_TOKEN}@github.com/${GH_REPO}.git" || true

            # Create GitHub Release
            curl -s -X POST \
              -H "Authorization: token ${GH_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"tag_name\":\"$TAG\", \"name\":\"$RELEASE_NAME\", \"body\":\"$BODY\", \"draft\":false, \"prerelease\":false}" \
              https://api.github.com/repos/${GH_REPO}/releases || true

            RELEASE_ID=$(curl -s -H "Authorization: token ${GH_TOKEN}" \
              https://api.github.com/repos/${GH_REPO}/releases/tags/$TAG | jq -r .id)

            # Upload assets
            curl -s -X POST \
              -H "Authorization: token ${GH_TOKEN}" \
              -H "Content-Type: application/gzip" \
              --data-binary @"$FILE" \
              "https://uploads.github.com/repos/${GH_REPO}/releases/$RELEASE_ID/assets?name=$FILE"

            curl -s -X POST \
              -H "Authorization: token ${GH_TOKEN}" \
              -H "Content-Type: text/plain" \
              --data-binary @"$FILE_SHA" \
              "https://uploads.github.com/repos/${GH_REPO}/releases/$RELEASE_ID/assets?name=$FILE_SHA"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build-neovim-arm64
