name: Build Neovim ARM64 v0.10.0

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and extract files
        run: |
          docker buildx build --platform linux/arm64 -t nvim-arm64 --output type=local,dest=output .

      - name: Create Git tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag -a v0.10.0-arm64 -m "Neovim ARM64 v0.10.0 build"
          git push origin v0.10.0-arm64

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.10.0-arm64
          name: Neovim ARM64 v0.10.0
          files: |
            output/nvim-arm64.tar.gz
            output/sha256.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
