name: Manual Build Neovim ARM64 (Auto Tag + Release)

on:
  workflow_dispatch:  # jalan manual (Run workflow)

permissions:
  contents: write

jobs:
  build-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Latest Neovim Version
        id: latest
        run: |
          LATEST=$(curl -s https://api.github.com/repos/neovim/neovim/releases/latest | jq -r .tag_name)
          echo "LATEST=$LATEST" >> $GITHUB_ENV
          echo "🔍 Latest Neovim version: $LATEST"

      - name: Check if tag already exists (local)
        run: |
          if git rev-parse "$LATEST-arm64" >/dev/null 2>&1; then
            echo "✅ Tag $LATEST-arm64 sudah ada (local), lanjut build ulang."
          fi

      - name: Set up QEMU for ARM64
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Neovim (${{ env.LATEST }} ARM64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --build-arg NEOVIM_VERSION=$LATEST \
            --build-arg MAKEFLAGS="-j2" \
            --output type=local,dest=. \
            .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nvim-arm64
          path: |
            nvim-arm64.tar.gz
            sha256.txt

      - name: Create & Push Tag (Force Replace if Exists)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if git ls-remote --tags origin | grep -q "$LATEST-arm64"; then
            echo "⚠️ Tag $LATEST-arm64 udah ada, hapus dulu dari remote..."
            git push --delete origin "$LATEST-arm64" || true
          fi
          git tag -fa "$LATEST-arm64" -m "Neovim ARM64 $LATEST (Auto Build)"
          git push origin "$LATEST-arm64"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.LATEST }}-arm64
          name: Neovim ARM64 ${{ env.LATEST }} (Auto Build)
          generate_release_notes: true
          overwrite: true       # ✅ ganti release lama kalau udah ada
          files: |
            nvim-arm64.tar.gz
            sha256.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
