name: Neovim Config CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Neovim
        uses: MunifTanjim/setup-neovim@v1
        with:
          neovim-version: nightly

      - name: Run health check
        run: nvim --headless "+checkhealth" +qa

      - name: Validate init.lua
        run: nvim --headless -c "luafile ~/.config/nvim/init.lua" +qa
